[development]
address = "localhost"
port = 8080
log = "normal"
limits = { forms = 32768 }
keep_alive = 5

[staging]
address = "0.0.0.0"
port = 80
log = "normal"
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 80
log = "critical"
limits = { forms = 32768 }